### ISSUE TITLE
jarbas version

### ISSUE THREAD

**Issue by JarbasAI** [normandmickey/skill-internet-radio#8]
i forked this and made a new version

it reads a folder from settings, in that folder is checks for "name.value" files , inside those it expects name , url pairs in csv format, this makes it super easy to add new stations

please have a look, i would create a PR but theres some massive changes, let me know if you are interested!

https://github.com/JarbasAl/skill-internet-radio

i am using my AudioSkill class to handle some stuff, so the code may not seem obvious in some parts

**Comment by normandmickey** [comment]
Go ahead and submit PR.  I knew it needed a lot of work and like what you
have done with it.

Thanks!

**Comment by normandmickey** [comment]
I cannot get your PR to merge so I just made you a collaborator of this repository.
